# -*- coding: utf-8 -*-
"""Copy of fcc_book_recommendation_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z34YnMqJ-DfjeK8WiXfQwbZ8ESzRkcW1
"""

# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

# Merge df_books and df_ratings
df = df_ratings.merge(df_books, on="isbn", how="left")

df.head(3)

# Display the number of rows and columns in the original DataFrame
df.shape

# Count how many reviews each user has left
users_counts = df["user"].value_counts()

# Count how many reviews each book (ISBN) has received
isbn_counts = df["isbn"].value_counts()

# Keep only users with 200 or more reviews
users = users_counts[users_counts >= 200].index

# Keep only books with 100 or more reviews
isbn = isbn_counts[isbn_counts >= 100].index

# Create a new DataFrame containing only rows where user and ISBN are in the filtered lists
df = df.loc[(df["user"].isin(users.values)) & (df["isbn"].isin(isbn.values))]

# Drop duplicate reviews
df = df.drop_duplicates(['title', 'user'])

df.isna().sum()

# Dropping isbns without title and author
df = df.dropna(how='any')

df.shape

# Create a pivot table
df_pivot = df.pivot(index = 'title', columns = 'user', values = 'rating').fillna(0)
df_pivot.head(3)

# Create a matrix
df_matrix = csr_matrix(df_pivot.values)

# Creating and training the model
nn = NearestNeighbors(metric='cosine')
nn.fit(df_matrix)

# function to return recommended books - this will be tested
def get_recommends(book = ""):
  # Create a list to put our model outputs into
  recommended_books = [book, []]

  # Pass through our book
  distance, book_info = nn.kneighbors([df_pivot.loc[book]], 6, return_distance=True)

  # Gather the text and distance & reverse the order
  recom_book_info = df_pivot.iloc[np.flip(book_info[0])[:-1]].index.to_list()
  recom_distance = list(np.flip(distance[0])[:-1])

  # for each value in our two variables append to our empty book list above
  for r in zip(recom_book_info, recom_distance):
    recommended_books[1].append(list(r))

  return recommended_books

# Test function
get_recommends('The Catcher in the Rye')

books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2):
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()